nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["*"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
    max_age: 3600
  paths:
    "^/": null
